import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import { AddFiiDialog } from './components/Dialogs/AddFiiDialog'
import { MagicNumberDialog } from './components/Dialogs/MagicNumberDialog'
import { Sidebar } from './components/Sidebar'
import { Topbar } from './components/Topbar'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'DiversiFIIque',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`flex bg-gray-950 ${inter.className}`}>
        <Sidebar />
        <div className="flex w-full flex-col">
          <Topbar />
          {children}
        </div>
        <div className="fixed bottom-6 right-6 flex flex-col gap-2">
          <MagicNumberDialog />
          <AddFiiDialog />
        </div>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  )
}
